create table public."Users" (
  id bigint generated by default as identity not null,
  telegram_chat_id bigint not null,
  name text not null,
  role text null default 'staff'::text,
  created_at timestamp with time zone null default now(),
  active_task_id bigint null,
  draft_assignee_id bigint null,
  outlet text null,
  constraint Users_pkey primary key (id),
  constraint Users_telegram_chat_id_key unique (telegram_chat_id)
) TABLESPACE pg_default;

create table public."Tasks" (
  id bigint generated by default as identity not null,
  telegram_chat_id bigint not null,
  task_name text not null,
  status text null default 'pending'::text,
  photo_url text null,
  created_at timestamp with time zone null default now(),
  completed_at timestamp with time zone null,
  assigned_by bigint null,
  outlet text null,
  constraint Tasks_pkey primary key (id),
  constraint Tasks_telegram_chat_id_fkey foreign KEY (telegram_chat_id) references "Users" (telegram_chat_id) on delete CASCADE
) TABLESPACE pg_default;

create table public."Master_Tasks" (
  id bigint generated by default as identity not null,
  task_name text not null,
  target_outlet text not null default 'GLOBAL'::text,
  is_active boolean not null default true,
  created_at timestamp with time zone not null default timezone ('utc'::text, now()),
  constraint Master_Tasks_pkey primary key (id)
) TABLESPACE pg_default;

create view public.vw_today_tasks as
select
  t.id as task_id,
  t.task_name,
  t.status,
  u.name as staff_name,
  (t.created_at AT TIME ZONE 'Asia/Makassar'::text) as created_at_wita,
  t.photo_url
from
  "Tasks" t
  join "Users" u on t.telegram_chat_id = u.telegram_chat_id
where
  (t.created_at AT TIME ZONE 'Asia/Makassar'::text)::date = (now() AT TIME ZONE 'Asia/Makassar'::text)::date;

create view public."Tasks_Recap_WITA" as
select
  t.id as task_id,
  t.task_name,
  t.status,
  u.name as staff_name,
  t.outlet,
  (t.created_at AT TIME ZONE 'Asia/Makassar'::text) as created_at_wita,
  (t.completed_at AT TIME ZONE 'Asia/Makassar'::text) as completed_at_wita,
  t.photo_url
from
  "Tasks" t
  join "Users" u on t.telegram_chat_id = u.telegram_chat_id;